include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = NightModeExtenderPrefs

NightModeExtenderPrefs_FILES = NMERootListController.m NMEDurationSliderCell.m
NightModeExtenderPrefs_INSTALL_PATH = /Library/PreferenceBundles
NightModeExtenderPrefs_FRAMEWORKS = UIKit
NightModeExtenderPrefs_PRIVATE_FRAMEWORKS = Preferences
NightModeExtenderPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
